CREATE TABLE IF NOT EXISTS "users" (
    "id" VARCHAR PRIMARY KEY,
    "first_name" VARCHAR NOT NULL,
    "last_name" VARCHAR NOT NULL,
    "email" VARCHAR NOT NULL UNIQUE,
    "password" VARCHAR NOT NULL,
    "role" VARCHAR NOT NULL,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS "posts" (
    "id" VARCHAR PRIMARY KEY,
    "user_id" VARCHAR NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    "title" VARCHAR NOT NULL,
    "body" VARCHAR NOT NULL,
    "published" BOOLEAN NOT NULL DEFAULT FALSE,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "comments" (
    "id" VARCHAR PRIMARY KEY,
    "user_id" VARCHAR NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    "post_id" VARCHAR NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
    "body" VARCHAR NOT NULL,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "saved_posts" (
    "id" VARCHAR PRIMARY KEY,
    "user_id" VARCHAR NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    "post_id" VARCHAR NOT NULL REFERENCES posts(id) ON DELETE CASCADE
);